### ISSUE TITLE
getData: parseDateTime returns Invalid format: ""

### ISSUE THREAD

**Issue by ghost** [Teevity/ice#210] opened 2016-05-06 10:49 UTC
ICE in a Docker container based on Jon Brouse's image used to work for months but now suddenly displays no graphs. The log shows an exception, similar to Issue 163 but the cause is different. The same happens when using Chrome and Firefox.

Log:

> | Error 2016-05-06 09:37:25,018 [http-nio-8080-exec-2] ERROR errors.GrailsExceptionResolver  - > IllegalArgumentException occurred when processing request: [POST] /ice/dashboard/getData
> Invalid format: "". Stacktrace follows:
> Message: Invalid format: ""
> Line | Method
> ->>  945 | parseDateTime in org.joda.time.format.DateTimeFormatter
> ---
> 
> |    407 | doGetData     in com.netflix.ice.DashboardController
> |    321 | doCall . . .  in com.netflix.ice.DashboardController$_closure11
> |   1145 | runWorker     in java.util.concurrent.ThreadPoolExecutor
> |    615 | run . . . . . in java.util.concurrent.ThreadPoolExecutor$Worker
> ^    745 | run           in java.lang.Thread
> 1462527445271
> | Error 2016-05-06 09:37:28,771 [http-nio-8080-exec-10] ERROR errors.GrailsExceptionResolver  - > IllegalArgumentException occurred when processing request: [POST] /ice/dashboard/getData
> Invalid format: "". Stacktrace follows:
> Message: Invalid format: ""
>     Line | Method
> ->>  945 | parseDateTime in org.joda.time.format.DateTimeFormatter
> ---
> 
> |    407 | doGetData     in com.netflix.ice.DashboardController
> |    321 | doCall . . .  in com.netflix.ice.DashboardController$_closure11
> |   1145 | runWorker     in java.util.concurrent.ThreadPoolExecutor
> |    615 | run . . . . . in java.util.concurrent.ThreadPoolExecutor$Worker
> ^    745 | run           in java.lang.Thread
> 1462527448992

Browser console shows that in the request body of getData, "start" and "end" are empty.
`{"isCost":true,"aggregate":"data","groupBy":"Product","consolidate":"monthly","start":"","end":"","breakdown":true,"showsps":false,"factorsps":false}`

I'd be glad for any advice.

**Comment by rayanimesh** [comment] 2016-05-06 11:59
Having same issue. Used to work fine till couple of days ago.  If you make a `POST` call with `start` and `end` parameters - it works.

**Comment by zette** [comment] 2016-05-06 12:17
I can confirm same behavior at my environment.
Modified POST works. I could not trace, place where `start` and `end` should be set in code.

**Comment by huit-tvachon** [comment] 2016-05-06 12:34
It just occurred here too.  It was working yesterday, and 18 hours later this is now happening.  I think we are tripping something in JS which was lurking

**Comment by rayanimesh** [comment] 2016-05-06 12:48
@huit-tvachon : Might be [hightchats JS](http://code.highcharts.com/stock/highstock.js). Does anybody have this file downloaded for serving over `https`?

**Comment by huit-tvachon** [comment] 2016-05-06 12:50
I'm trying pinning it to 4.2.1 in my ice.properties now.  It was updated this morning to 4.2.2

I am using: https://code.highcharts.com/stock/4.2.1/highstock.js

**Comment by huit-tvachon** [comment] 2016-05-06 12:58
@rayanimesh and @zette that fixed the issue

**Comment by rayanimesh** [comment] 2016-05-06 13:01
@huit-tvachon Yes. Working now.

**Comment by frankshimizu** [comment] 2016-05-06 13:02
Thanks very much for these pointers. I restarted ICE with the older 4.2.1 and it's working here as well.

**Comment by interactivetech** [comment] 2016-05-06 19:09
This worked for me as well. Thanks...just in time for an important demo!

**Comment by jonbrouse** [comment] 2016-05-07 17:36
thank you @jonhadfield I merged the change. There is now a v2.1 image with the change on the docker hub.

**Comment by ghaber** [comment] 2016-05-08 15:01
Hi,

With version 4.2.4 of highstocks it is still working, change affecting ICE is 4.2.5, I guess in line 482:

line 482      
* Check for number
* @param {Object} n*/
-    function isNumber(n) {
-        return typeof n === 'number';
-    }
+    var isNumber = Highcharts.isNumber = function isNumber(n) {
+        return typeof n === 'number' && !isNaN(n);
+    };

line 676:
 * @param {Boolean} capitalize
      */
     dateFormat = function (format, timestamp, capitalize) {
-        if (!defined(timestamp) || isNaN(timestamp)) {
+        if (!isNumber(timestamp)) {
             return defaultOptions.lang.invalidDate || '';
         }
         format = pick(format, '%Y-%m-%d %H:%M:%S');

in particular in line 680 where invalidDate is said.

Yo can see whole differences of 4.2.4 and 4.2.5 in link:

[https://github.com/highcharts/highcharts/compare/master@%7B3%20weeks%7D...master#diff-72973c1959312806279557c1b7e06c35L1](url)

Regards

**Comment by liukedong** [comment] 2016-05-09 03:11
See the same problem this morning. @ghaber thanks for your solution.

**Comment by pj-moviestarplanet** [comment] 2016-05-09 09:06
We also had this problem since last week. Thanks to @ghaber for coming up with a solution that works.

Remember to docker compose rm the containers as a restart wont take into account the ice properties changes.

**Comment by pexaorj** [comment] 2016-05-30 17:13
I have the same problem, solved by @ghaber hotfix :) thanks a lot

**Closed** 2017-06-07 15:49 UTC
